### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by artephius** [kchmck/scrape-fcc#1]
Running your scrape-fcc script, on 
File "C:\Users\jeff\Documents\GitHub\scrape-fcc-env\uls.py", line 30, in __iter__
  table = soup.select("table[summary~=License]")[0]
I get 
builtins.IndexError: list index out of range 

This scraper would help me out big time if I can get it to work.
Please advise.

**Comment by kchmck** [comment]
Hey @artephius, could you post the state/county you're trying it with? I just tried it with a few counties in ohio, and it seems to be working with those.

**Comment by kchmck** [comment]
I also added some `raise_for_status` checks around the HTTP requests, so you might pull in the latest changes and try another scrape. It's possible an HTTP error was being suppressed.

**Comment by artephius** [comment]
@kchmck, I tried it with a few counties in Colorado.
I'll grab the latest and let you know. 
Thanks!

**Comment by kchmck** [comment]
This might be fixed by 7cf830af5b55e669057ef00a298ca178df5616b2

**Comment by artephius** [comment]
Updated and I'm watching it add records as I write this.
[7cf830a](https://github.com/kchmck/scrape-fcc/commit/7cf830af5b55e669057ef00a298ca178df5616b2) was the fix.

You, sir, are the man!
Thank you!

**Comment by kchmck** [comment]
Awesome, let me know if you have any other issues or if there's some additional information you'd like added to the scrapes.
